version: '2.2'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root123'
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql  
  interview-localstack:
    image: localstack/localstack
    ports:
      - "4567-4597:4567-4597"
    environment:
      - DEFAULT_REGION=ap-southeast-1
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  my-db:
