version: '2.2'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'BAoMDUdhcmFudGlh'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - my-db:/var/lib/mysql
  localstack:
    container_name: localstack
    image: localstack/localstack
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=ap-southeast-1
    ports:
      - "4567-4582:4567-4582"
      - "8081:8081"  
  python_container:
    container_name: aws_sqs_app
    build:
      context: .
      dockerfile: runnerDockerfile
    environment:
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_DEFAULT_REGION=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
    links:
      - localstack
      - db
    stdin_open: true # docker run -i
    tty: true        # docker run -t
volumes:
  my-db:
